name: test-phoenixdb-online-store
on: [push, pull_request]
jobs:
  test-phoenixdb-online-store:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
        os: [ ubuntu-latest, macOS-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Set up MySQL
        uses: docker.io/cheyuanl/opdb
      - name: Set up PhoenixDB database
        run: |
          /opt/opdb-start
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest test_phoenixdb_online_store.py
